#!/usr/bin/env bash

music_folder="$1"

# Ask if the user wants to shuffle
echo 'Do you want to shuffle the playing? (y/n):'
read -r shuffle

# Determine the playlist command based on shuffle preference
if [[ "$shuffle" == "y" || "$shuffle" == "Y" ]]; then
    mpv "$music_folder" --no-video --hwdec=auto --shuffle --term-osd-bar --vo=null --no-resume-playback
    # flatpak run io.mpv.Mpv "$music_folder" --no-video --hwdec=auto --shuffle --term-osd-bar --vo=null --no-resume-playback
else
    mpv "$music_folder" --no-video --hwdec=auto --term-osd-bar --vo=null --no-resume-playback
    # flatpak run io.mpv.Mpv "$music_folder" --no-video --hwdec=auto --term-osd-bar --vo=null --no-resume-playback
fi
