#!/usr/bin/env bash

yt_link=$1

if [[ -z "$yt_link" ]]; then
    echo "Error: No link provided."
    exit 1
fi

# Check if the link is valid using yt-dlp
yt-dlp --get-id "$yt_link" &>/dev/null
if [[ $? -ne 0 ]]; then
    echo "Error: Invalid link or unable to fetch video information."
    exit 1
fi

echo '


▗▖  ▗▖▗▄▄▖ ▗▖  ▗▖▗▖  ▗▖▗▄▄▄▖
▐▛▚▞▜▌▐▌ ▐▌▐▌  ▐▌ ▝▚▞▘   █
▐▌  ▐▌▐▛▀▘ ▐▌  ▐▌  ▐▌    █
▐▌  ▐▌▐▌    ▝▚▞▘   ▐▌    █ by rycane


'

echo 'Fetching video formats...'
# Getting available video/stream formats
yt-dlp -F "$yt_link"

# Ask user to enter the target format
echo 'Please enter the desired format (e.g., 22 for 720p):'
read -r format

# Ask user if they want audio only
echo 'Do you want to play audio only? (y/n):'
read -r audio_only

# Determine the format option based on user input
if [[ "$audio_only" == "y" ]]; then
    mpv "$yt_link" --ytdl-format="bestaudio" --term-osd-bar
    # flatpak run io.mpv.Mpv "$yt_link" --ytdl-format="bestaudio" --term-osd-bar
else
    mpv "$yt_link" --ytdl-format="$format" --hwdec=auto --term-osd-bar
    # flatpak run io.mpv.Mpv "$yt_link" --ytdl-format="$format" --hwdec=auto --term-osd-bar
fi
